language: elixir
elixir:
  - 1.3.1
  - 1.4.0
  - 1.6.6
  - 1.7.3
otp_release:
  - 17.5
  - 18.0
  - 19.0
before_script:
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
services:
  - redis-server
sudo: required
